### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by kadirgund**
- Deleted the property babel from state along with references to it 
- Deleted console.logs that caused crashes
- Tied the checked property of all radios and checkboxes of all selections to the value of their state
- Altered useEffect hook to update the steps at each selection to prevent the issue of no render

### CODE REVIEW

**Review by CaliskanBurak — APPROVED** [review]
Approved.

**Review by taylordu — APPROVED** [review]
Approved

**Review by patrick934 — CHANGES_REQUESTED** [review]
Please uninstall 'axios' and delete useMemo from App.jsx

**Comment by kadirgund** [comment]
Made the requested changes and some other improvements.

**Review by patrick934 — APPROVED** [review]
Approved

**Review by CaliskanBurak — APPROVED** [review]
Approved the latest changes

**Pull request merged**
